import { describe, expect, it } from "vitest";
import { compileClaude } from "../../src/compiler/claude.js";
import type { Sot, Rule } from "../../src/types.js";

const HEADER = "<!-- Generated by agents-doc; do not edit. Source: .agents-doc/ -->\n";

function rule(partial: Partial<Rule> & { filename: string; body: string }): Rule {
  return {
    frontmatter: { agents: ["*"], priority: "normal", path: ".", ...(partial.frontmatter ?? {}) },
    ...partial,
  };
}

function sot(rules: Rule[]): Sot {
  return { config: { agents: ["claude", "codex"] }, rules, skills: [], commands: [] };
}

describe("compileClaude rules", () => {
  it("concatenates rules at the root path into CLAUDE.md with the gen header", () => {
    const out = compileClaude(
      sot([
        rule({ filename: "a.md", body: "# A\nbody A\n" }),
        rule({ filename: "b.md", body: "# B\nbody B\n" }),
      ]),
    );
    const content = out.files.get("CLAUDE.md")!.toString("utf8");
    expect(content).toBe(HEADER + "# A\nbody A\n\n# B\nbody B\n");
  });

  it("orders rules high → normal → low, then by filename", () => {
    const out = compileClaude(
      sot([
        rule({ filename: "z.md", body: "Z\n", frontmatter: { agents: ["*"], priority: "low", path: "." } }),
        rule({ filename: "a.md", body: "A\n", frontmatter: { agents: ["*"], priority: "normal", path: "." } }),
        rule({ filename: "h.md", body: "H\n", frontmatter: { agents: ["*"], priority: "high", path: "." } }),
        rule({ filename: "h2.md", body: "H2\n", frontmatter: { agents: ["*"], priority: "high", path: "." } }),
      ]),
    );
    const content = out.files.get("CLAUDE.md")!.toString("utf8");
    expect(content).toBe(HEADER + "H\n\nH2\n\nA\n\nZ\n");
  });

  it("emits one file per unique path", () => {
    const out = compileClaude(
      sot([
        rule({ filename: "root.md", body: "root\n" }),
        rule({ filename: "nested.md", body: "nested\n", frontmatter: { agents: ["*"], priority: "normal", path: "src/app" } }),
      ]),
    );
    expect([...out.files.keys()].sort()).toEqual([".claude/commands/doc-fix.md", "CLAUDE.md", "src/app/CLAUDE.md"]);
  });

  it("excludes rules scoped to other agents", () => {
    const out = compileClaude(
      sot([
        rule({ filename: "claude.md", body: "claude only\n", frontmatter: { agents: ["claude"], priority: "normal", path: "." } }),
        rule({ filename: "codex.md", body: "codex only\n", frontmatter: { agents: ["codex"], priority: "normal", path: "." } }),
      ]),
    );
    const content = out.files.get("CLAUDE.md")!.toString("utf8");
    expect(content).toBe(HEADER + "claude only\n");
  });

  it("normalizes CRLF in rule bodies to LF", () => {
    const out = compileClaude(sot([rule({ filename: "a.md", body: "line1\r\nline2\r\n" })]));
    const content = out.files.get("CLAUDE.md")!.toString("utf8");
    expect(content).toBe(HEADER + "line1\nline2\n");
  });

  it("emits only built-ins when there are no claude-scoped rules", () => {
    const out = compileClaude(
      sot([rule({ filename: "x.md", body: "x\n", frontmatter: { agents: ["codex"], priority: "normal", path: "." } })]),
    );
    expect([...out.files.keys()]).toEqual([".claude/commands/doc-fix.md"]);
  });

  it("includes rules with explicit multi-agent list ['claude','codex']", () => {
    const out = compileClaude(
      sot([
        rule({ filename: "shared.md", body: "shared body\n", frontmatter: { agents: ["claude", "codex"], priority: "normal", path: "." } }),
      ]),
    );
    const content = out.files.get("CLAUDE.md")!.toString("utf8");
    expect(content).toBe(HEADER + "shared body\n");
  });

  it("orders rules at a nested path: high → normal → low, then by filename", () => {
    const out = compileClaude(
      sot([
        rule({ filename: "z.md", body: "Z\n", frontmatter: { agents: ["*"], priority: "low", path: "src/app" } }),
        rule({ filename: "a.md", body: "A\n", frontmatter: { agents: ["*"], priority: "normal", path: "src/app" } }),
        rule({ filename: "h.md", body: "H\n", frontmatter: { agents: ["*"], priority: "high", path: "src/app" } }),
      ]),
    );
    const content = out.files.get("src/app/CLAUDE.md")!.toString("utf8");
    expect(content).toBe(HEADER + "H\n\nA\n\nZ\n");
  });
});
