import { describe, expect, it } from "vitest";
import { compileCodex } from "../../src/compiler/codex.js";
import type { Sot, Rule } from "../../src/types.js";

const HEADER = "<!-- Generated by agents-doc; do not edit. Source: .agents-doc/ -->\n";

function rule(partial: Partial<Rule> & { filename: string; body: string }): Rule {
  return {
    frontmatter: { agents: ["*"], priority: "normal", path: ".", ...(partial.frontmatter ?? {}) },
    ...partial,
  };
}

function sot(rules: Rule[]): Sot {
  return { config: { agents: ["claude", "codex"] }, rules, skills: [], commands: [] };
}

// `compileCodex` always emits the built-in doc-fix skill alongside the
// rule output; these rule-focused tests filter it out so they stay
// scoped to AGENTS.md compilation.
const isAgentsMd = (k: string) => k.endsWith("AGENTS.md");

describe("compileCodex rules", () => {
  it("emits AGENTS.md per unique path", () => {
    const out = compileCodex(
      sot([
        rule({ filename: "root.md", body: "root\n" }),
        rule({ filename: "nested.md", body: "nested\n", frontmatter: { agents: ["*"], priority: "normal", path: "src/app" } }),
      ]),
    );
    expect([...out.files.keys()].filter(isAgentsMd).sort()).toEqual(["AGENTS.md", "src/app/AGENTS.md"]);
    expect(out.files.get("AGENTS.md")!.toString("utf8")).toBe(HEADER + "root\n");
  });

  it("excludes claude-only rules", () => {
    const out = compileCodex(
      sot([
        rule({ filename: "c.md", body: "c\n", frontmatter: { agents: ["claude"], priority: "normal", path: "." } }),
      ]),
    );
    expect([...out.files.keys()].filter(isAgentsMd)).toEqual([]);
  });

  it("includes rules with explicit multi-agent list ['claude','codex']", () => {
    const out = compileCodex(
      sot([
        rule({ filename: "shared.md", body: "shared body\n", frontmatter: { agents: ["claude", "codex"], priority: "normal", path: "." } }),
      ]),
    );
    const content = out.files.get("AGENTS.md")!.toString("utf8");
    expect(content).toBe(HEADER + "shared body\n");
  });
});
