import { describe, expect, it } from "vitest";
import yaml from "js-yaml";
import { compileCursor } from "../../src/compiler/cursor.js";
import { compile } from "../../src/compiler/index.js";
import type { Rule, Sot } from "../../src/types.js";

const HEADER = "<!-- Generated by agents-doc; do not edit. Source: .agents-doc/ -->\n";

function rule(partial: Partial<Rule> & { filename: string; body: string }): Rule {
  return {
    frontmatter: { agents: ["*"], priority: "normal", path: ".", ...(partial.frontmatter ?? {}) },
    ...partial,
  };
}

function sot(rules: Rule[]): Sot {
  return { config: { agents: ["cursor"] }, rules, skills: [], commands: [] };
}

function extractFrontmatter(content: string): Record<string, unknown> {
  const m = /^---\n([\s\S]*?)\n---\n/.exec(content);
  if (!m) throw new Error(`no frontmatter in:\n${content}`);
  return yaml.load(m[1]) as Record<string, unknown>;
}

describe("compileCursor rules", () => {
  it("emits one .mdc per rule at .cursor/rules/", () => {
    const out = compileCursor(
      sot([
        rule({ filename: "001-intro.md", body: "intro body\n" }),
        rule({ filename: "002-style.md", body: "style body\n" }),
      ]),
    );
    const keys = [...out.files.keys()].sort();
    expect(keys).toEqual([
      ".cursor/rules/001-intro.mdc",
      ".cursor/rules/002-style.mdc",
    ]);
  });

  it("root-path rule with no globs sets alwaysApply: true", () => {
    const out = compileCursor(sot([rule({ filename: "a.md", body: "always body\n" })]));
    const content = out.files.get(".cursor/rules/a.mdc")!.toString("utf8");
    expect(content).toMatch(/^---\nalwaysApply: true\n---\n/);
    expect(content).toContain(HEADER);
    expect(content).toContain("always body");
  });

  it("excludes rules not scoped to cursor", () => {
    const out = compileCursor(
      sot([
        rule({
          filename: "claude-only.md",
          body: "c\n",
          frontmatter: { agents: ["claude"], priority: "normal", path: "." },
        }),
      ]),
    );
    expect([...out.files.keys()]).toEqual([]);
  });

  it("includes rules with explicit agents: [cursor]", () => {
    const out = compileCursor(
      sot([
        rule({
          filename: "c.md",
          body: "c body\n",
          frontmatter: { agents: ["cursor"], priority: "normal", path: "." },
        }),
      ]),
    );
    expect(out.files.has(".cursor/rules/c.mdc")).toBe(true);
  });

  it("passes explicit globs through and sets alwaysApply: false", () => {
    const out = compileCursor(
      sot([
        rule({
          filename: "g.md",
          body: "g\n",
          frontmatter: {
            agents: ["*"],
            priority: "normal",
            path: ".",
            globs: ["src/**/*.ts"],
          },
        }),
      ]),
    );
    const fm = extractFrontmatter(out.files.get(".cursor/rules/g.mdc")!.toString("utf8"));
    expect(fm.globs).toEqual(["src/**/*.ts"]);
    expect(fm.alwaysApply).toBe(false);
  });

  it("derives globs from non-root path when explicit globs are absent", () => {
    const out = compileCursor(
      sot([
        rule({
          filename: "p.md",
          body: "p\n",
          frontmatter: {
            agents: ["*"],
            priority: "normal",
            path: "src/components",
          },
        }),
      ]),
    );
    const fm = extractFrontmatter(out.files.get(".cursor/rules/p.mdc")!.toString("utf8"));
    expect(fm.globs).toEqual(["src/components/**"]);
    expect(fm.alwaysApply).toBe(false);
  });

  it("explicit globs override path-derived globs", () => {
    const out = compileCursor(
      sot([
        rule({
          filename: "po.md",
          body: "po\n",
          frontmatter: {
            agents: ["*"],
            priority: "normal",
            path: "src/components",
            globs: ["src/**/*.tsx"],
          },
        }),
      ]),
    );
    const fm = extractFrontmatter(out.files.get(".cursor/rules/po.mdc")!.toString("utf8"));
    expect(fm.globs).toEqual(["src/**/*.tsx"]);
  });

  it("passes description through when present, omits when absent", () => {
    const withDesc = compileCursor(
      sot([
        rule({
          filename: "d.md",
          body: "d\n",
          frontmatter: {
            agents: ["*"],
            priority: "normal",
            path: ".",
            description: "When working with X",
          },
        }),
      ]),
    );
    const fm1 = extractFrontmatter(withDesc.files.get(".cursor/rules/d.mdc")!.toString("utf8"));
    expect(fm1.description).toBe("When working with X");

    const withoutDesc = compileCursor(sot([rule({ filename: "x.md", body: "x\n" })]));
    const fm2 = extractFrontmatter(withoutDesc.files.get(".cursor/rules/x.mdc")!.toString("utf8"));
    expect(fm2.description).toBeUndefined();
  });

  it("body is LF-normalized and starts with the gen header after frontmatter", () => {
    const out = compileCursor(
      sot([rule({ filename: "n.md", body: "line one\r\nline two\r\n" })]),
    );
    const content = out.files.get(".cursor/rules/n.mdc")!.toString("utf8");
    // No CRLF in output.
    expect(content.includes("\r")).toBe(false);
    // Frontmatter, then header, then body.
    expect(content).toMatch(/^---\n[\s\S]*?\n---\n<!-- Generated/);
    expect(content).toContain("line one\nline two");
  });
});

describe("compile() with cursor enabled", () => {
  it("includes cursor outputs alongside claude when both agents are enabled", () => {
    const out = compile({
      config: { agents: ["claude", "cursor"] },
      rules: [
        {
          filename: "shared.md",
          frontmatter: { agents: ["*"], priority: "normal", path: "." },
          body: "shared\n",
        },
      ],
      skills: [],
      commands: [],
    });
    expect(out.files.has("CLAUDE.md")).toBe(true);
    expect(out.files.has(".cursor/rules/shared.mdc")).toBe(true);
  });

  it("omits cursor outputs when cursor is not in config.agents", () => {
    const out = compile({
      config: { agents: ["claude"] },
      rules: [
        {
          filename: "shared.md",
          frontmatter: { agents: ["*"], priority: "normal", path: "." },
          body: "shared\n",
        },
      ],
      skills: [],
      commands: [],
    });
    expect([...out.files.keys()].some((k) => k.startsWith(".cursor/"))).toBe(false);
  });
});
