import { Agent, Rule } from "../types.js";

export const GEN_HEADER =
  "<!-- Generated by agents-doctor; do not edit. Source: .agents-doctor/ -->\n";

const PRIORITY_RANK: Record<Rule["frontmatter"]["priority"], number> = {
  high: 0,
  normal: 1,
  low: 2,
};

export function rulesForAgent(rules: Rule[], agent: Agent): Rule[] {
  return rules.filter((r) => {
    const a = r.frontmatter.agents;
    if (a.length === 1 && a[0] === "*") return true;
    return (a as Agent[]).includes(agent);
  });
}

export function groupByPath(rules: Rule[]): Map<string, Rule[]> {
  const out = new Map<string, Rule[]>();
  for (const r of rules) {
    const path = r.frontmatter.path;
    const list = out.get(path) ?? [];
    list.push(r);
    out.set(path, list);
  }
  for (const list of out.values()) sortRules(list);
  return out;
}

function sortRules(rules: Rule[]): void {
  rules.sort((a, b) => {
    const pr = PRIORITY_RANK[a.frontmatter.priority] - PRIORITY_RANK[b.frontmatter.priority];
    if (pr !== 0) return pr;
    return a.filename.localeCompare(b.filename);
  });
}

export function concatBodies(rules: Rule[]): string {
  return rules.map((r) => stripTrailingNewlines(normalizeLf(r.body))).join("\n\n") + "\n";
}

function stripTrailingNewlines(s: string): string {
  return s.replace(/\n+$/, "");
}

export function normalizeLf(s: string): string {
  return s.replace(/\r\n/g, "\n");
}

export function joinPath(dir: string, filename: string): string {
  if (dir === "" || dir === ".") return filename;
  return `${dir.replace(/\/+$/, "")}/${filename}`;
}
