import { mkdirSync, writeFileSync } from "node:fs";
import { join } from "node:path";
import type { BucketMap, ClassifiedIssue } from "./classify.js";
import type { LintIssue, LintLocation } from "../lint/types.js";

export const TODO_HEADER =
  "<!-- Generated by agents-doc doctor; do not edit. Run /doc-fix to work through. -->";

type NowFn = () => Date;

const defaultNow: NowFn = () => new Date();

export function renderTodo(buckets: BucketMap, now: NowFn = defaultNow): string {
  const decisive = buckets.decisive;
  const generative = buckets.generative;
  const total = decisive.length + generative.length;

  const lines: string[] = [];
  lines.push(TODO_HEADER);
  lines.push("# agents-doc todo");
  lines.push("");
  const stamp = now().toISOString().slice(0, 10);
  lines.push(
    `_Generated ${stamp} by \`agents-doc doctor\`. ${total} item(s) need a human or AI judgment._`,
  );
  lines.push("");

  if (decisive.length > 0) {
    lines.push(`## Decisive (${decisive.length})`);
    lines.push("");
    for (const issue of decisive) lines.push(...renderEntry(issue));
    lines.push("");
  }

  if (generative.length > 0) {
    lines.push(`## Generative (${generative.length})`);
    lines.push("");
    for (const issue of generative) lines.push(...renderEntry(issue));
    lines.push("");
  }

  return lines.join("\n");
}

export function writeTodo(buckets: BucketMap, projectRoot: string, now: NowFn = defaultNow): string {
  const dir = join(projectRoot, ".agents-doc");
  mkdirSync(dir, { recursive: true });
  const path = join(dir, ".todo.md");
  writeFileSync(path, renderTodo(buckets, now), "utf8");
  return path;
}

function renderEntry(issue: ClassifiedIssue): string[] {
  if (issue.kind === "drift") {
    return [
      `- [ ] **drift** \`${issue.source.path}\` — ${issue.source.kind}`,
    ];
  }
  return renderLintEntry(issue.source);
}

function renderLintEntry(li: LintIssue): string[] {
  const out: string[] = [];
  const loc = formatLocation(li.location);
  const related = (li.related ?? []).map(formatLocation);
  const path = related.length > 0 ? `${loc} ↔ ${related.join(" ↔ ")}` : loc;
  out.push(`- [ ] **${li.category}** ${path} — ${li.message}`);
  if (li.suggestion) out.push(`  - suggestion: ${li.suggestion}`);
  return out;
}

function formatLocation(loc: LintLocation): string {
  const lineSuffix = loc.line !== undefined ? `:${loc.line}` : "";
  return `\`rules/${loc.ruleFile}${lineSuffix}\``;
}
