import { existsSync, mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { join } from "node:path";
import type { BucketMap, ClassifiedIssue } from "./classify.js";
import type { LintIssue, LintLocation } from "../lint/types.js";

export const TODO_HEADER =
  "<!-- Generated by agents-doc doctor. Run /doc-fix to work through; checkbox updates are OK. -->";

type NowFn = () => Date;

const defaultNow: NowFn = () => new Date();

const CHECKED_LINE_RE = /^- \[x\] (.+?)\s*$/;

function extractCheckedSignatures(content: string): Set<string> {
  const sigs = new Set<string>();
  for (const line of content.split(/\r?\n/)) {
    const m = CHECKED_LINE_RE.exec(line);
    if (m && m[1]) sigs.add(m[1]);
  }
  return sigs;
}

export function renderTodo(
  buckets: BucketMap,
  now: NowFn = defaultNow,
  previousContent?: string,
): string {
  const checked = previousContent
    ? extractCheckedSignatures(previousContent)
    : new Set<string>();

  const decisive = buckets.decisive;
  const generative = buckets.generative;
  const total = decisive.length + generative.length;

  const lines: string[] = [];
  lines.push(TODO_HEADER);
  lines.push("# agents-doc todo");
  lines.push("");
  const stamp = now().toISOString().slice(0, 10);
  lines.push(
    `_Generated ${stamp} by \`agents-doc doctor\`. ${total} item(s) need a human or AI judgment._`,
  );
  lines.push("");

  if (decisive.length > 0) {
    lines.push(`## Decisive (${decisive.length})`);
    lines.push("");
    for (const issue of decisive) lines.push(...renderEntry(issue, checked));
    lines.push("");
  }

  if (generative.length > 0) {
    lines.push(`## Generative (${generative.length})`);
    lines.push("");
    for (const issue of generative) lines.push(...renderEntry(issue, checked));
    lines.push("");
  }

  return lines.join("\n");
}

export function writeTodo(buckets: BucketMap, projectRoot: string, now: NowFn = defaultNow): string {
  const dir = join(projectRoot, ".agents-doc");
  mkdirSync(dir, { recursive: true });
  const path = join(dir, "todo.md");
  const previous = existsSync(path) ? readFileSync(path, "utf8") : undefined;
  writeFileSync(path, renderTodo(buckets, now, previous), "utf8");
  return path;
}

function renderEntry(issue: ClassifiedIssue, checked: Set<string>): string[] {
  if (issue.kind === "drift") {
    const sig = `**drift** \`${issue.source.path}\` — ${issue.source.kind}`;
    return [`- [${mark(sig, checked)}] ${sig}`];
  }
  return renderLintEntry(issue.source, checked);
}

function renderLintEntry(li: LintIssue, checked: Set<string>): string[] {
  const out: string[] = [];
  const loc = formatLocation(li.location);
  const related = (li.related ?? []).map(formatLocation);
  const path = related.length > 0 ? `${loc} ↔ ${related.join(" ↔ ")}` : loc;
  const sig = `**${li.category}** ${path} — ${li.message}`;
  out.push(`- [${mark(sig, checked)}] ${sig}`);
  if (li.suggestion) out.push(`  - suggestion: ${li.suggestion}`);
  return out;
}

function mark(sig: string, checked: Set<string>): string {
  return checked.has(sig) ? "x" : " ";
}

function formatLocation(loc: LintLocation): string {
  const lineSuffix = loc.line !== undefined ? `:${loc.line}` : "";
  return `\`rules/${loc.ruleFile}${lineSuffix}\``;
}
