import { describe, expect, it } from "vitest";
import { existsSync, readFileSync, readdirSync } from "node:fs";
import { join } from "node:path";
import matter from "gray-matter";
import { runInit } from "../../src/commands/init.js";
import { makeTmpDir, writeFile } from "../helpers/tmp.js";
import type { SelectAgentFn } from "../../src/prompt.js";

const stubSelect: SelectAgentFn = async () => "claude";

function findRule(rulesDir: string, suffix: string): string {
  const file = readdirSync(rulesDir).find((f) => f.endsWith(suffix));
  if (!file) throw new Error(`no rule ending with ${suffix} in ${rulesDir}`);
  return join(rulesDir, file);
}

describe("runInit", () => {
  it("aborts non-zero if .agents-doctor/ already exists", async () => {
    const root = makeTmpDir();
    writeFile(root, ".agents-doctor/config.yaml", "agents: [claude]\n");
    await expect(runInit({ projectRoot: root, selectAgent: stubSelect })).rejects.toThrow(/already/);
  });

  it("aborts when CLAUDE.md has duplicate ## headings", async () => {
    const root = makeTmpDir();
    writeFile(root, "CLAUDE.md", "## Style\nA\n## Style\nB\n");
    await expect(runInit({ projectRoot: root, selectAgent: stubSelect })).rejects.toThrow(
      /CLAUDE\.md has duplicate '## Style'/,
    );
    // .agents-doctor/ should not be partially created.
    expect(existsSync(join(root, ".agents-doctor"))).toBe(false);
  });

  it("aborts when AGENTS.md has duplicate intro (pre-heading) content", async () => {
    const root = makeTmpDir();
    // Two intro-equivalent chunks would require duplicate heading-less segments,
    // which splitByH2 collapses by design — so use a duplicate ## heading on AGENTS.md instead.
    writeFile(root, "AGENTS.md", "## Lint\nfirst\n## Lint\nsecond\n");
    await expect(runInit({ projectRoot: root, selectAgent: stubSelect })).rejects.toThrow(
      /AGENTS\.md has duplicate '## Lint'/,
    );
  });

  it("aborts when nested CLAUDE.md has duplicate ## headings (path is in the message)", async () => {
    const root = makeTmpDir();
    writeFile(root, "src/app/CLAUDE.md", "## A\nfoo\n## A\nbar\n");
    await expect(runInit({ projectRoot: root, selectAgent: stubSelect })).rejects.toThrow(
      /src\/app\/CLAUDE\.md has duplicate '## A'/,
    );
  });

  it("aborts when there are no agent files anywhere", async () => {
    const root = makeTmpDir();
    writeFile(root, "README.md", "nothing useful\n");
    await expect(runInit({ projectRoot: root, selectAgent: stubSelect })).rejects.toThrow(
      /no agent files/,
    );
  });

  it("seeds from .claude/skills only, with no rule files", async () => {
    const root = makeTmpDir();
    writeFile(
      root,
      ".claude/skills/refactor-py/SKILL.md",
      "---\nname: refactor-py\ndescription: refactor\n---\n# body\n",
    );
    const result = await runInit({ projectRoot: root, selectAgent: stubSelect });
    expect(result.rulesEmitted).toBe(0);
    expect(existsSync(join(root, ".agents-doctor/skills/refactor-py/SKILL.md"))).toBe(true);
    // config.yaml exists with claude only.
    const cfg = readFileSync(join(root, ".agents-doctor/config.yaml"), "utf8");
    expect(cfg).toContain("claude");
    expect(cfg).not.toContain("codex");
    // The skill's SKILL.md should be regenerated by sync.
    expect(existsSync(join(root, ".claude/skills/refactor-py/SKILL.md"))).toBe(true);
  });

  it("creates SOT from CLAUDE.md only at root, preserving section order", async () => {
    const root = makeTmpDir();
    writeFile(root, "CLAUDE.md", "intro\n## Style\nuse spaces\n");
    await runInit({ projectRoot: root, selectAgent: stubSelect });

    expect(existsSync(join(root, ".agents-doctor/config.yaml"))).toBe(true);
    const ruleFiles = readdirSync(join(root, ".agents-doctor/rules")).sort();
    expect(ruleFiles).toHaveLength(2);
    expect(ruleFiles[0]).toMatch(/^000-.*intro\.md$/);
    expect(ruleFiles[1]).toMatch(/^001-.*style\.md$/);

    const style = matter(readFileSync(findRule(join(root, ".agents-doctor/rules"), "-style.md"), "utf8"));
    expect(style.data.agents).toEqual(["claude"]);
    expect(style.content).toContain("## Style");
    expect(style.content).toContain("use spaces");
  });

  it("merges identical chunks across CLAUDE.md and AGENTS.md as agents: ['*']", async () => {
    const root = makeTmpDir();
    writeFile(root, "CLAUDE.md", "## Style\nuse spaces\n");
    writeFile(root, "AGENTS.md", "## Style\nuse spaces\n");
    await runInit({ projectRoot: root, selectAgent: stubSelect });
    const style = matter(readFileSync(findRule(join(root, ".agents-doctor/rules"), "-style.md"), "utf8"));
    expect(style.data.agents).toEqual(["*"]);
  });

  it("priority agent wins on conflicting chunks", async () => {
    const root = makeTmpDir();
    writeFile(root, "CLAUDE.md", "## Style\nuse spaces\n");
    writeFile(root, "AGENTS.md", "## Style\nuse tabs\n");
    await runInit({ projectRoot: root, selectAgent: async () => "claude" });
    const style = matter(readFileSync(findRule(join(root, ".agents-doctor/rules"), "-style.md"), "utf8"));
    expect(style.data.agents).toEqual(["claude"]);
    expect(style.content).toContain("use spaces");
    expect(style.content).not.toContain("use tabs");
  });

  it("priority codex wins on conflicting chunks (symmetric path)", async () => {
    const root = makeTmpDir();
    writeFile(root, "CLAUDE.md", "## Style\nuse spaces\n");
    writeFile(root, "AGENTS.md", "## Style\nuse tabs\n");
    await runInit({ projectRoot: root, selectAgent: async () => "codex" });
    const style = matter(readFileSync(findRule(join(root, ".agents-doctor/rules"), "-style.md"), "utf8"));
    expect(style.data.agents).toEqual(["codex"]);
    expect(style.content).toContain("use tabs");
    expect(style.content).not.toContain("use spaces");
  });

  it("scopes single-side chunks to their originating agent", async () => {
    const root = makeTmpDir();
    writeFile(root, "CLAUDE.md", "## Only Claude\nbody\n");
    writeFile(root, "AGENTS.md", "## Only Codex\nbody\n");
    await runInit({ projectRoot: root, selectAgent: stubSelect });
    const rulesDir = join(root, ".agents-doctor/rules");
    const onlyClaude = matter(readFileSync(findRule(rulesDir, "-only-claude.md"), "utf8"));
    expect(onlyClaude.data.agents).toEqual(["claude"]);
    const onlyCodex = matter(readFileSync(findRule(rulesDir, "-only-codex.md"), "utf8"));
    expect(onlyCodex.data.agents).toEqual(["codex"]);
  });

  it("emits path: frontmatter for nested CLAUDE.md", async () => {
    const root = makeTmpDir();
    writeFile(root, "src/app/CLAUDE.md", "## Local\nlocal body\n");
    await runInit({ projectRoot: root, selectAgent: stubSelect });
    const ruleFiles = readdirSync(join(root, ".agents-doctor/rules"));
    expect(ruleFiles).toHaveLength(1);
    const rule = matter(readFileSync(join(root, ".agents-doctor/rules", ruleFiles[0]!), "utf8"));
    expect(rule.data.path).toBe("src/app");
  });

  it("copies skills and commands verbatim into the SOT", async () => {
    const root = makeTmpDir();
    writeFile(root, "CLAUDE.md", "intro\n");
    writeFile(root, ".claude/skills/refactor-py/SKILL.md", "---\nname: refactor-py\ndescription: refactor\n---\n# body\n");
    writeFile(root, ".claude/skills/refactor-py/scripts/run.sh", "echo hi\n");
    writeFile(root, ".claude/commands/review.md", "---\ndescription: r\n---\nreview body\n");
    await runInit({ projectRoot: root, selectAgent: stubSelect });
    expect(existsSync(join(root, ".agents-doctor/skills/refactor-py/SKILL.md"))).toBe(true);
    expect(existsSync(join(root, ".agents-doctor/skills/refactor-py/scripts/run.sh"))).toBe(true);
    expect(existsSync(join(root, ".agents-doctor/commands/review.md"))).toBe(true);
  });

  it("preserves section order through init → sync", async () => {
    const root = makeTmpDir();
    // Headings whose alphabetical order does NOT match discovery order:
    //   discovery: intro → Banana → Apple → Cherry
    //   alphabetical of slugs: apple, banana, cherry, intro
    writeFile(
      root,
      "CLAUDE.md",
      "intro line\n## Banana\nbody B\n## Apple\nbody A\n## Cherry\nbody C\n",
    );
    await runInit({ projectRoot: root, selectAgent: stubSelect });

    const compiled = readFileSync(join(root, "CLAUDE.md"), "utf8");
    const introIdx = compiled.indexOf("intro line");
    const bananaIdx = compiled.indexOf("## Banana");
    const appleIdx = compiled.indexOf("## Apple");
    const cherryIdx = compiled.indexOf("## Cherry");
    expect(introIdx).toBeGreaterThan(-1);
    expect(bananaIdx).toBeGreaterThan(introIdx);
    expect(appleIdx).toBeGreaterThan(bananaIdx);
    expect(cherryIdx).toBeGreaterThan(appleIdx);
  });

  it("runs sync immediately and the result passes check", async () => {
    const root = makeTmpDir();
    writeFile(root, "CLAUDE.md", "## A\nbody\n");
    writeFile(root, "AGENTS.md", "## A\nbody\n");
    await runInit({ projectRoot: root, selectAgent: stubSelect });
    const claude = readFileSync(join(root, "CLAUDE.md"), "utf8");
    expect(claude).toMatch(/^<!-- Generated by agents-doctor;/);
    const { runCheck } = await import("../../src/commands/check.js");
    const r = await runCheck({ projectRoot: root });
    expect(r.ok).toBe(true);
  });

  it("ignores CLAUDE.md and AGENTS.md inside .claude/ during discovery", async () => {
    const root = makeTmpDir();
    writeFile(root, "CLAUDE.md", "## Real\nbody\n");
    // A skill folder happens to ship a CLAUDE.md as docs — must NOT be treated as a rule.
    writeFile(root, ".claude/skills/foo/SKILL.md", "---\nname: foo\n---\n");
    writeFile(root, ".claude/skills/foo/CLAUDE.md", "stray docs\n");
    writeFile(root, ".claude/skills/foo/AGENTS.md", "stray docs\n");

    const result = await runInit({ projectRoot: root, selectAgent: stubSelect });

    // Only one rule from the real root CLAUDE.md.
    expect(result.rulesEmitted).toBe(1);
    const ruleFiles = readdirSync(join(root, ".agents-doctor/rules"));
    expect(ruleFiles).toHaveLength(1);
  });

  it("returns a summary of rules emitted and files synced", async () => {
    const root = makeTmpDir();
    writeFile(root, "CLAUDE.md", "intro\n## A\nbody\n## B\nbody\n");
    writeFile(root, "AGENTS.md", "intro\n## A\nbody\n## B\nbody\n");
    const result = await runInit({ projectRoot: root, selectAgent: stubSelect });
    // 3 chunks (intro, A, B), so 3 rules emitted.
    expect(result.rulesEmitted).toBe(3);
    // sync should write CLAUDE.md and AGENTS.md.
    expect(result.filesWritten.sort()).toEqual(["AGENTS.md", "CLAUDE.md"]);
  });
});
