import { describe, expect, it } from "vitest";
import { existsSync, readFileSync, readdirSync } from "node:fs";
import { join } from "node:path";
import matter from "gray-matter";
import { runInit } from "../../src/commands/init.js";
import { makeTmpDir, writeFile } from "../helpers/tmp.js";
import type { SelectAgentFn } from "../../src/prompt.js";

const stubSelect: SelectAgentFn = async () => "claude";

describe("runInit", () => {
  it("aborts non-zero if .agents-doctor/ already exists", async () => {
    const root = makeTmpDir();
    writeFile(root, ".agents-doctor/config.yaml", "agents: [claude]\n");
    await expect(runInit({ projectRoot: root, selectAgent: stubSelect })).rejects.toThrow(/already/);
  });

  it("creates SOT from CLAUDE.md only at root", async () => {
    const root = makeTmpDir();
    writeFile(root, "CLAUDE.md", "intro\n## Style\nuse spaces\n");
    await runInit({ projectRoot: root, selectAgent: stubSelect });

    expect(existsSync(join(root, ".agents-doctor/config.yaml"))).toBe(true);
    const ruleFiles = readdirSync(join(root, ".agents-doctor/rules"));
    expect(ruleFiles.sort()).toEqual(["intro.md", "style.md"]);

    const style = matter(readFileSync(join(root, ".agents-doctor/rules/style.md"), "utf8"));
    expect(style.data.agents).toEqual(["claude"]);
    expect(style.content).toContain("## Style");
    expect(style.content).toContain("use spaces");
  });

  it("merges identical chunks across CLAUDE.md and AGENTS.md as agents: ['*']", async () => {
    const root = makeTmpDir();
    writeFile(root, "CLAUDE.md", "## Style\nuse spaces\n");
    writeFile(root, "AGENTS.md", "## Style\nuse spaces\n");
    await runInit({ projectRoot: root, selectAgent: stubSelect });
    const style = matter(readFileSync(join(root, ".agents-doctor/rules/style.md"), "utf8"));
    expect(style.data.agents).toEqual(["*"]);
  });

  it("priority agent wins on conflicting chunks", async () => {
    const root = makeTmpDir();
    writeFile(root, "CLAUDE.md", "## Style\nuse spaces\n");
    writeFile(root, "AGENTS.md", "## Style\nuse tabs\n");
    await runInit({ projectRoot: root, selectAgent: async () => "claude" });
    const style = matter(readFileSync(join(root, ".agents-doctor/rules/style.md"), "utf8"));
    expect(style.data.agents).toEqual(["claude"]);
    expect(style.content).toContain("use spaces");
    expect(style.content).not.toContain("use tabs");
  });

  it("scopes single-side chunks to their originating agent", async () => {
    const root = makeTmpDir();
    writeFile(root, "CLAUDE.md", "## Only Claude\nbody\n");
    writeFile(root, "AGENTS.md", "## Only Codex\nbody\n");
    await runInit({ projectRoot: root, selectAgent: stubSelect });
    const onlyClaude = matter(readFileSync(join(root, ".agents-doctor/rules/only-claude.md"), "utf8"));
    expect(onlyClaude.data.agents).toEqual(["claude"]);
    const onlyCodex = matter(readFileSync(join(root, ".agents-doctor/rules/only-codex.md"), "utf8"));
    expect(onlyCodex.data.agents).toEqual(["codex"]);
  });

  it("emits path: frontmatter for nested CLAUDE.md", async () => {
    const root = makeTmpDir();
    writeFile(root, "src/app/CLAUDE.md", "## Local\nlocal body\n");
    await runInit({ projectRoot: root, selectAgent: stubSelect });
    const ruleFiles = readdirSync(join(root, ".agents-doctor/rules"));
    expect(ruleFiles).toHaveLength(1);
    const rule = matter(readFileSync(join(root, ".agents-doctor/rules", ruleFiles[0]!), "utf8"));
    expect(rule.data.path).toBe("src/app");
  });

  it("copies skills and commands verbatim into the SOT", async () => {
    const root = makeTmpDir();
    writeFile(root, "CLAUDE.md", "intro\n");
    writeFile(root, ".claude/skills/refactor-py/SKILL.md", "---\nname: refactor-py\ndescription: refactor\n---\n# body\n");
    writeFile(root, ".claude/skills/refactor-py/scripts/run.sh", "echo hi\n");
    writeFile(root, ".claude/commands/review.md", "---\ndescription: r\n---\nreview body\n");
    await runInit({ projectRoot: root, selectAgent: stubSelect });
    expect(existsSync(join(root, ".agents-doctor/skills/refactor-py/SKILL.md"))).toBe(true);
    expect(existsSync(join(root, ".agents-doctor/skills/refactor-py/scripts/run.sh"))).toBe(true);
    expect(existsSync(join(root, ".agents-doctor/commands/review.md"))).toBe(true);
  });

  it("runs sync immediately and the result passes check", async () => {
    const root = makeTmpDir();
    writeFile(root, "CLAUDE.md", "## A\nbody\n");
    writeFile(root, "AGENTS.md", "## A\nbody\n");
    await runInit({ projectRoot: root, selectAgent: stubSelect });
    const claude = readFileSync(join(root, "CLAUDE.md"), "utf8");
    expect(claude).toMatch(/^<!-- Generated by agents-doctor;/);
    const { runCheck } = await import("../../src/commands/check.js");
    const r = await runCheck({ projectRoot: root });
    expect(r.ok).toBe(true);
  });
});
