import { describe, expect, it } from "vitest";
import { readFileSync } from "node:fs";
import { join } from "node:path";
import { runSync } from "../../src/commands/sync.js";
import { makeTmpDir, writeFile } from "../helpers/tmp.js";

describe("runSync", () => {
  it("writes Claude and Codex files from SOT", async () => {
    const root = makeTmpDir();
    writeFile(root, ".agents-doc/config.yaml", "agents: [claude, codex]\n");
    writeFile(root, ".agents-doc/rules/general.md", "---\n---\n# General\nbody\n");

    const result = await runSync({ projectRoot: root });
    expect(result.written.sort()).toEqual(["AGENTS.md", "CLAUDE.md"]);

    const claude = readFileSync(join(root, "CLAUDE.md"), "utf8");
    expect(claude).toMatch(/^<!-- Generated by agents-doc;/);
    expect(claude).toContain("# General");
    const codex = readFileSync(join(root, "AGENTS.md"), "utf8");
    expect(codex).toContain("# General");
  });

  it("overwrites existing files unconditionally", async () => {
    const root = makeTmpDir();
    writeFile(root, ".agents-doc/config.yaml", "agents: [claude]\n");
    writeFile(root, ".agents-doc/rules/x.md", "---\n---\nnew\n");
    writeFile(root, "CLAUDE.md", "stale\n");

    await runSync({ projectRoot: root });
    expect(readFileSync(join(root, "CLAUDE.md"), "utf8")).toContain("new");
    expect(readFileSync(join(root, "CLAUDE.md"), "utf8")).not.toContain("stale");
  });

  it("creates nested parent directories", async () => {
    const root = makeTmpDir();
    writeFile(root, ".agents-doc/config.yaml", "agents: [claude]\n");
    writeFile(
      root,
      ".agents-doc/rules/nested.md",
      "---\npath: src/app\n---\nbody\n",
    );
    await runSync({ projectRoot: root });
    expect(readFileSync(join(root, "src/app/CLAUDE.md"), "utf8")).toContain("body");
  });
});
